# Generated by Django 3.1.7 on 2021-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshipQuestions', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
