# Generated by Django 3.1.7 on 2021-03-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendshipQuestions', '0003_quiz_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
