# Generated by Django 3.1.7 on 2021-03-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendshipQuestions', '0004_auto_20210316_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='friendshipQuestions.quiz')),
            ],
        ),
    ]
