# Generated by Django 3.1.7 on 2021-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
