# Generated by Django 3.1.7 on 2021-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_choice_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_image",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
